IyilikCatisi.WebCoreUI/Areas/AdminPanel/Controllers/YoneticiController.cs
using Infrastructure.CrossCuttingConcern.Converters;
using Infrastructure.CrossCuttingConcern.Crypto;
using Infrastructure.Utility;
using System.Drawing;
using IyilikCatisi.Business.Abstract;
using IyilikCatisi.Model.Entity;
using IyilikCatisi.Model.ViewModel.Areas.AdminPanel;
using IyilikCatisi.WebCoreUI.Filters;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;

namespace IyilikCatisi.WebCoreUI.Areas.AdminPanel.Controllers
{
    [Area("AdminPanel")]
    public class YoneticiController : Controller
    {
        private readonly IKullanicilarBS _kullaniciBS;
        private readonly ISessionManager _session;
        IMemoryCache _cache;
        public YoneticiController(IKullanicilarBS kullaniciBS, ISessionManager session, IMemoryCache cache)
        {
            _kullaniciBS = kullaniciBS;
            _session = session;
			_cache = cache;
        
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Login()
        {

            string? Id = HttpContext.Request.Cookies["AktifYoneticiCookie"];
            if (!string.IsNullOrEmpty(Id))
            {

                int kid = Convert.ToInt32(Id);
                Kullanicilar k = _kullaniciBS.Get(x => x.Id == kid);
                if (k != null)
                {
                    _session.AktifYonetici = k;
                    return RedirectToAction("Index", "Panel");


                }



            }
            LoginVm vm = new LoginVm();

            return View(vm); 
        }

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Login(LoginVm kullanici)
		{
			kullanici.Email = "vektorelyazilimsinanhoca@gmail.com";
			kullanici.Sifre = "Sinan2590@";

			//if (!ModelState.IsValid)
			//{
			//    return View(kullanici);
			//}


			//string guvenlikkodu = _session.GuvenlikKodu;
			//if (kullanici.GuvenlikKodu != guvenlikkodu)
			//{
			//    TempData["Mesaj"] = "GüvenlikKodu Hatalı. ";
			//    return View();
			//}

			string CryptoPassword = CryptoManager.SHA256Encrypt(kullanici.Sifre);
			Kullanicilar kullanici1 = _kullaniciBS.Get(x => x.Email == kullanici.Email && x.Sifre == CryptoPassword,false,"KullaniciRols","KullaniciRols.Rol");

			if (kullanici1 != null)
			{

				_session.AktifYonetici = kullanici1;

                // _cache.Set<Kullanici>("Aktif", _session.AktifYonetici);


                CookieOptions options = new CookieOptions();
                options.Expires = DateTime.Now.AddYears(1); //Ben yok etmezsem sen 1 yıl dursun sonra kendiliğinden silinsin
                HttpContext.Response.Cookies.Append("AktifYoneticiCookie", kullanici1.Id.ToString(), options);

                return RedirectToAction("Index", "Panel");
			}

			else
			{
				TempData["Mesaj"] = "Giriş Hatalı";
			}



			return View();
		}
		public IActionResult GetCaptcha()
		{
			CaptchaGenerator captcha = new CaptchaGenerator(6, "Verdana", 20);
			Bitmap b = captcha.GuvenlikResmiUret();
			_session.GuvenlikKodu = captcha.olusturanString;

			byte[] imagebyte = Converters.ImageToByteArray(b);


			return File(imagebyte, "image/jpg");
		}
        public IActionResult Logout()
        {
            _session.AktifYonetici = null;

            HttpContext.Response.Cookies.Delete("AktifYoneticiCookie");


            return RedirectToAction("Login");
        }
        public IActionResult YetkinizYok()
        {
            return View();
        }
    }
}

IyilikCatisi.WebCoreUI/Areas/AdminPanel/Views/Yonetici/Login.cshtml
@{
    Layout = null;
}
@model LoginVm
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>SparkMarket Yönetici Girişi</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/adminassets/plugins/fontawesome-free/css/all.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="~/adminassets/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/adminassets/css/adminlte.min.css">
</head>
<body class="hold-transition login-page">
    <div class="login-box">
        <!-- /.login-logo -->
        <div class="card card-outline card-primary">
            <div class="card-header text-center">
                <a href="../../index2.html" class="h1"><b>SparkMarket</b> Admin Panel</a>
            </div>
            <div class="card-body">
                <p class="login-box-msg pb-0">Lütfen giriş yapınız...</p>

                @* <form action="Login" method="post"> *@
                <form id="frmLogin" asp-action="Login" asp-controller="Yonetici" asp-area="AdminPanel" method="post" asp-antiforgery="true">

                   @*  <div asp-validation-summary="All" class="mt-0 mb-0"></div> *@ @* Nasıl istediğimiz mesajları yazdırırız? *@

                    @* Email *@
                    <div class="input-group mb-3">
                        <input type="email" asp-for="Email" class="form-control" placeholder="Eposta">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-envelope"></span>
                            </div>
                        </div>
                        
                    </div>
                    <span asp-validation-for="Email"></span>

                    @* Şifre *@
                    <div class="input-group mb-3 mt-3">
                        <input type="password" asp-for="Sifre" class="form-control" placeholder="Şifre">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                        
                    </div>
                    <span asp-validation-for="Sifre"></span>

                    @* Captcha *@
                    <div class="input-group mt-3 mb-3">
                        <input type="text" asp-for="GuvenlikKodu" class="form-control" placeholder="GüvenlikKodu">
                        <img id="GuvenlikKoduImage" src="/AdminPanel/Yonetici/GetCaptcha" />
                        <img id="GuvenlikKoduRefresh" width="30" height="30" style="cursor:pointer;" onclick="RefreshCaptcha();" src="~/adminassets/img/refresh.png" />
                    </div>

                    @* Beni Hatırla ve Giriş Yap *@
                    <div class="row">
                        <div class="col-8">
                            <div class="icheck-primary">
                                <input type="checkbox" asp-for="BeniHatirla" id="remember">
                                <label for="remember">
                                    Beni Hatırla
                                </label>
                            </div>
                        </div>
                        <!-- /.col -->
                        <div class="col-4">
                            <button type="submit" class="btn btn-primary btn-block">Giriş Yap</button>
                            @TempData["Mesaj"]
                        </div>
                        <!-- /.col -->
                    </div>
                </form>


                <p class="mb-1">
                    <a href="forgot-password.html">Şifremi unuttum</a>
                </p>
                <p class="mb-0">
                    <a href="register.html" class="text-center">Yeni bir üyelik oluştur</a>
                </p>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
    <!-- /.login-box -->
    <!-- jQuery -->
    <script src="~/adminassets/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/adminassets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/adminassets/js/adminlte.min.js"></script>


    <script src="~/adminassets/plugins/jquery-validation/jquery.validate.min.js"></script>

    <script src="~/adminassets/plugins/jquery-validation/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>


    <script>
        function RefreshCaptcha() {
            var id = Math.random();
            $("#GuvenlikKoduImage").attr("src", "/AdminPanel/Yonetici/GetCaptcha?id=" + id);
        }
    </script>
</body>
</html>

IyilikCatisi.WebCoreUI/Areas/AdminPanel/Views/Yonetici/YetkinizYok.cshtml
@section ContentHeader
{



}


<div class="alert alert-danger">
    Bu sayfayı görüntülemeye yetkiniz bulunmamaktadır.

</div>